<?php

declare(strict_types=1);

/*
 |=============================================================================
 | Wajhatak — Fix Property Images (standalone maintenance script)
 |=============================================================================
 | Makes every property's images exist on the server disk at the exact
 | relative path stored in `property_images.path`, and binds each property to
 | its local files. A property never ends up with a broken 404 image URL.
 |
 | Why this exists:
 |   - Railway (and most PaaS) use an ephemeral disk: files written by the
 |     seeder are wiped on every redeploy/restart, so stored URLs return 404
 |     even though the database rows are intact (reprovisioning is skipped).
 |   - Some networks in Yemen cannot reach some public CDNs (Unsplash, etc.),
 |     so HTTP fetching alone is not a reliable fix. This script therefore
 |     uses a chain of sources and ALWAYS ends with a fully offline image
 |     generated by GD — the final result never depends on the network.
 |
 | Result: every `property_images.path` points to a real JPEG under
 | storage/app/public (served at {APP_URL}/storage/{path}), and images whose
 | paths were absolute external URLs are rebound to local files.
 |
 | Run it (from backend/):
 |   php scripts/fix_property_images.php                          fill gaps only
 |   php scripts/fix_property_images.php --dry-run                preview, change nothing
 |   php scripts/fix_property_images.php --regen                  re-render every image
 |   php scripts/fix_property_images.php --property=SN-2026-001   one property (ID or code)
 |   php scripts/fix_property_images.php --property=12 --regen
 |   php scripts/fix_property_images.php --limit=5                process first N properties
 |
 | On Railway:
 |   railway run php scripts/fix_property_images.php
 | or enable the self-healing hook: set environment variable
 |   WJ_RUN_IMAGE_FIX=1   (entrypoint runs this script on every boot, idempotent)
 |=============================================================================
 */

use App\Models\Property;
use App\Models\PropertyImage;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\Storage;

$root = dirname(__DIR__);
require $root.'/vendor/autoload.php';
$app = require $root.'/bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

/*
 |------------------------------------------------------------------------------
 | Configuration
 |------------------------------------------------------------------------------
 */
const IMAGE_MAX_WIDTH = 1280;
const IMAGE_QUALITY = 82;
const IMAGES_PER_PROPERTY = 3;

// Stable Unsplash photo IDs (same visual families used by RealDataSeeder).
$COVERS = [
    '1580587771525-78b9dba3b914', '1568605114967-8130f3a36994',
    '1570129477492-45c003edd2be', '1600596542815-ffad4c1539a9',
    '1600585154340-be6161a56a0c', '1600566753190-17f0baa2a6c3',
    '1600047509807-ba8f99d2cdde', '1613490493576-7fde63acd811',
    '1545324418-cc1a3fa10c00', '1512917774080-9991f1c4c750',
    '1575517111478-7f6afd0973db', '1502005229762-cf1b2da7c5d6',
    '1470770841072-f978cf4d019e', '1523217582562-09d0def993a6',
    '1570126618953-d437176e8c79',
];
$INTERIORS = [
    '1600607687939-ce8a6c25118c', '1600210492486-724fe5c67fb0',
    '1605348532760-6753d2c43329', '1493809842364-78817add7ffb',
    '1522708323590-d24dbb6b0267', '1502672260266-1c1ef2d93688',
    '1484154218962-a197022b5858', '1554995207-c18c203602cb',
    '1560448204-e02f11c3d0e2', '1522444195799-478538b28823',
    '1460317442991-0ec209397118', '1605276374104-dee2a0ed3cd6',
    '1512453979798-5ea266f8880c', '1560518883-ce09059eeffa',
    '1486406146926-c627a92ad1ab',
];

/*
 |------------------------------------------------------------------------------
 | CLI argument parsing
 |------------------------------------------------------------------------------
 */
$dryRun = false;
$regen = false;
$onlyProperty = null;
$limit = PHP_INT_MAX;
$quiet = false;

foreach (array_slice($_SERVER['argv'], 1) as $arg) {
    if ($arg === '--dry-run') {
        $dryRun = true;
    } elseif ($arg === '--regen' || $arg === '--force') {
        $regen = true;
    } elseif (str_starts_with($arg, '--property=')) {
        $onlyProperty = substr($arg, strlen('--property='));
    } elseif (str_starts_with($arg, '--limit=')) {
        $limit = max(1, (int) substr($arg, strlen('--limit=')));
    } elseif ($arg === '--quiet') {
        $quiet = true;
    } else {
        fwrite(STDERR, "Unknown argument: $arg\n");
        fwrite(STDERR, "Usage: php scripts/fix_property_images.php [--dry-run] [--regen] [--property=ID|CODE] [--limit=N] [--quiet]\n");
        exit(2);
    }
}

/*
 |------------------------------------------------------------------------------
 | Helpers
 |------------------------------------------------------------------------------
 */
function logLine(string $message, bool $quiet): void
{
    if (! $quiet) {
        echo '[fix-images] '.$message.PHP_EOL;
    }
}

/** GET a URL body using cURL with a stream-context fallback. */
function httpGet(string $url): ?string
{
    $userAgent = 'Wajhatak/ImageFix (+https://wajhatak.app)';
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS => 3,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_USERAGENT => $userAgent,
            CURLOPT_HTTPHEADER => ['Accept: image/*,*/*;q=0.8'],
        ]);
        $body = curl_exec($ch);
        $code = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
        curl_close($ch);
        if (is_string($body) && $code >= 200 && $code < 300 && strlen($body) > 0) {
            return $body;
        }
    }
    $ctx = stream_context_create([
        'http' => [
            'timeout' => 30,
            'ignore_errors' => true,
            'user_agent' => $userAgent,
            'header' => "User-Agent: $userAgent\r\nAccept: image/*,*/*;q=0.8\r\n",
        ],
        'ssl' => ['verify_peer' => true, 'verify_peer_name' => true],
    ]);
    $body = @file_get_contents($url, false, $ctx);
    return is_string($body) && strlen($body) > 0 ? $body : null;
}

/** Decode + downscale to JPEG at the destination. Returns true on success. */
function renderJpeg(string $bytes, string $dest, int $maxWidth, int $quality): bool
{
    $img = @imagecreatefromstring($bytes);
    if ($img === false) {
        return false;
    }
    $w = imagesx($img);
    $h = imagesy($img);
    if ($w > $maxWidth && $h > 0) {
        $nw = $maxWidth;
        $nh = max(1, (int) round($h * $maxWidth / $w));
        $resized = imagecreatetruecolor($nw, $nh);
        imagecopyresampled($resized, $img, 0, 0, 0, 0, $nw, $nh, $w, $h);
        imagedestroy($img);
        $img = $resized;
    }
    $dir = dirname($dest);
    if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
        imagedestroy($img);
        return false;
    }
    $ok = imagejpeg($img, $dest, $quality);
    imagedestroy($img);
    return $ok && is_file($dest) && filesize($dest) > 0;
}

/** Fully offline branded placeholder (gradient + translucent shapes + text). */
function makePlaceholder(string $dest, string $label, int $maxWidth, int $quality): bool
{
    $w = 1280;
    $h = 800;
    $img = imagecreatetruecolor($w, $h);
    $top = [12, 92, 68];
    $bottom = [22, 142, 116];
    for ($y = 0; $y < $h; $y++) {
        $t = $y / $h;
        $r = (int) ($top[0] + ($bottom[0] - $top[0]) * $t);
        $g = (int) ($top[1] + ($bottom[1] - $top[1]) * $t);
        $b = (int) ($top[2] + ($bottom[2] - $top[2]) * $t);
        $line = imagecolorallocate($img, $r, $g, $b);
        imageline($img, 0, $y, $w, $y, $line);
        imagecolordeallocate($img, $line);
    }
    $white = imagecolorallocatealpha($img, 255, 255, 255, 110);
    $soft = imagecolorallocatealpha($img, 255, 255, 255, 60);
    for ($i = 0; $i < 3; $i++) {
        imagefilledellipse(
            $img,
            (int) ($w * (0.2 + $i * 0.3)),
            (int) ($h * (0.3 + $i * 0.2)),
            (int) (420 - $i * 60),
            (int) (420 - $i * 60),
            $i % 2 === 0 ? $white : $soft
        );
    }
    $whiteText = imagecolorallocate($img, 255, 255, 255);
    $label = $label !== '' ? $label : 'وجهتك العقارية';
    $font = dirname(__DIR__).'/public/fonts/Amiri-Bold.ttf';
    $topText = 'وجهتك العقارية';
    if (is_file($font)) {
        @imagettftext($img, 44, 0, 60, 100, $whiteText, $font, $topText);
        @imagettftext($img, 30, 0, 60, $h - 60, $whiteText, $font, $label);
    } else {
        imagestring($img, 4, 60, 60, 'Wajhatak', $whiteText);
        imagestring($img, 4, 60, $h - 60, $label, $whiteText);
    }
    if ($w > $maxWidth) {
        $nw = $maxWidth;
        $nh = (int) round($h * $maxWidth / $w);
        $resized = imagecreatetruecolor($nw, $nh);
        imagecopyresampled($resized, $img, 0, 0, 0, 0, $nw, $nh, $w, $h);
        imagedestroy($img);
        $img = $resized;
        $w = $nw;
    }
    $dir = dirname($dest);
    if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
        imagedestroy($img);
        return false;
    }
    $ok = imagejpeg($img, $dest, $quality);
    imagedestroy($img);
    return $ok && is_file($dest) && filesize($dest) > 0;
}

/** Deterministic numeric key for a property (from reference code or id). */
function numericKey(string $ref, int $id): int
{
    preg_match_all('/\d+/', $ref, $m);
    $digits = implode('', $m[0] ?? []);
    $n = $digits !== '' ? (int) $digits : $id;
    return $n === 0 ? $id : $n;
}

/**
 * Source chain for one image slot. Tried in order; every step returns raw bytes
 * or null, and the caller falls back to a GD placeholder that always succeeds.
 *
 * @return string[] list of URL candidates
 */
function candidateSources(int $propKey, int $slot, array $covers, array $interiors): array
{
    $coverId = $covers[$propKey % count($covers)];
    $interiorId1 = $interiors[$propKey % count($interiors)];
    $interiorId2 = $interiors[($propKey + 5) % count($interiors)];
    $seed = 'wj-'.$propKey.'-'.$slot;
    $id = $slot === 0 ? $coverId : ($slot === 1 ? $interiorId1 : $interiorId2);
    $unsplash = "https://images.unsplash.com/photo-{$id}?auto=format&fit=crop&w=".IMAGE_MAX_WIDTH.'&q=78';
    return [
        $unsplash,
        "https://picsum.photos/seed/{$seed}/".IMAGE_MAX_WIDTH.'/800.jpg',
        "https://loremflickr.com/".IMAGE_MAX_WIDTH.'/800/house,interior?lock='.($propKey * 10 + $slot),
    ];
}

function propertyLabel(\App\Models\Property $property): string
{
    return $property->reference_code ?: ('ID '.$property->id);
}

/*
 |------------------------------------------------------------------------------
 | Main
 |------------------------------------------------------------------------------
 */
$disk = Storage::disk('public');
$publicRoot = realpath($disk->path('')) ?: $disk->path('');
logLine('Public disk root: '.$publicRoot, $quiet);
logLine('Mode: '.($dryRun ? 'DRY-RUN (no changes)' : ($regen ? 'regenerate all' : 'fill missing only')), $quiet);

$query = Property::query()->whereNull('deleted_at')->orderBy('id');
if ($onlyProperty !== null) {
    $column = ctype_digit((string) $onlyProperty) ? 'id' : 'reference_code';
    $query->where($column, $onlyProperty);
}

$stats = [
    'properties' => 0,
    'images_ok' => 0,
    'images_downloaded' => 0,
    'images_placeholder' => 0,
    'images_failed' => 0,
    'records_created' => 0,
    'paths_rebound' => 0,
    'covers_set' => 0,
];

$properties = $query->limit($limit)->get();
logLine('Total properties to process: '.$properties->count(), $quiet);

foreach ($properties as $property) {
    $stats['properties']++;
    $label = propertyLabel($property);
    logLine("--- {$label} (id={$property->id})", $quiet);

    $records = $property->images()->orderBy('sort_order')->orderBy('id')->get();

    // Determine the canonical folder. Prefer the folder already used by the
    // first record; otherwise follow the convention used by seeds/uploads.
    $firstPath = $records->first()?->path;
    $folder = $firstPath !== null && $firstPath !== ''
        ? ltrim(dirname($firstPath), './')
        : ($property->reference_code
            ? 'properties/real/'.$property->reference_code
            : 'properties/'.$property->id);
    $folder = trim($folder, '/');
    if ($folder === '') {
        $folder = 'properties/'.$property->id;
    }
    logLine('    folder: '.$folder, $quiet);

    // 1) Ensure at least N image records exist for this property.
    if ($records->isEmpty()) {
        for ($slot = 0; $slot < IMAGES_PER_PROPERTY; $slot++) {
            if (! $dryRun) {
                $records->push(PropertyImage::create([
                    'property_id' => $property->id,
                    'path' => $folder."/{$slot}.jpg",
                    'sort_order' => $slot,
                    'is_cover' => $slot === 0,
                    'alt_text' => $property->reference_code ? "عقار {$property->reference_code}" : 'عقار',
                ]));
                $stats['records_created']++;
            }
        }
        $records = $property->images()->orderBy('sort_order')->orderBy('id')->get();
    }

    $hasCover = (bool) $records->contains(fn (PropertyImage $img) => $img->is_cover);
    $propKey = numericKey((string) $property->reference_code, (int) $property->id);

    // 2) Ensure every record has a real local file at the exact stored path.
    foreach ($records as $index => $image) {
        $stored = $image->path;
        $targetPath = trim(ltrim((string) $stored, '/\\'), '/');
        if ($targetPath === '') {
            $targetPath = $folder."/{$index}.jpg";
        }

        // Rebind absolute external URLs to local relative paths.
        if (preg_match('#^https?://#i', (string) $stored)) {
            logLine("    rebind {$image->id}: absolute URL -> {$folder}/{$index}.jpg", $quiet);
            $targetPath = $folder."/{$index}.jpg";
            if (! $dryRun) {
                $image->path = $targetPath;
                $image->save();
                $stats['paths_rebound']++;
            }
        }

        $abs = $disk->path($targetPath);
        $needsFetch = $regen || ! is_file($abs) || filesize($abs) === 0;

        if (! $needsFetch) {
            $stats['images_ok']++;
            logLine("    {$targetPath} OK (already on disk)", $quiet);
            $thisSlot = $index;
        } else {
            $thisSlot = $index;
            $bytes = null;
            foreach (candidateSources($propKey, $thisSlot, $COVERS, $INTERIORS) as $url) {
                logLine("    fetch #{$thisSlot}: {$url}", $quiet);
                $fetched = httpGet($url);
                if ($fetched !== null) {
                    $tmp = tempnam(sys_get_temp_dir(), 'wjimg');
                    if ($tmp !== false && renderJpeg($fetched, $tmp, IMAGE_MAX_WIDTH, IMAGE_QUALITY)) {
                        $bytes = file_get_contents($tmp);
                        @unlink($tmp);
                        if ($bytes !== null && strlen($bytes) > 0) {
                            break;
                        }
                    }
                    $bytes = null;
                    @unlink((string) $tmp);
                }
            }

            if ($bytes !== null && ! $dryRun && $disk->put($targetPath, $bytes)) {
                $stats['images_downloaded']++;
                logLine("    {$targetPath} downloaded", $quiet);
            } elseif ($bytes !== null && $dryRun) {
                $stats['images_downloaded']++;
                logLine("    {$targetPath} would be downloaded", $quiet);
            } else {
                logLine("    fell back to offline placeholder", $quiet);
                if (! $dryRun && ! makePlaceholder($abs, propertyLabel($property), IMAGE_MAX_WIDTH, IMAGE_QUALITY)) {
                    $stats['images_failed']++;
                    logLine("    !! could not write {$targetPath}", $quiet);
                    continue;
                }
                $stats['images_placeholder']++;
                if ($dryRun) {
                    logLine("    {$targetPath} would use placeholder", $quiet);
                }
            }
        }

        // 3) Bind the record to the actual local file (idempotent).
        if (! $dryRun && $image->path !== $targetPath) {
            $image->path = $targetPath;
            $image->save();
            $stats['paths_rebound']++;
        }

        // 4) Normalize cover flag when the property has none.
        if ($index === 0 && ! $hasCover && ! $dryRun && ! $image->is_cover) {
            $image->is_cover = true;
            $image->save();
            $stats['covers_set']++;
            logLine("    set cover on {$targetPath}", $quiet);
        }
    }
}

/*
 |------------------------------------------------------------------------------
 | Report
 |------------------------------------------------------------------------------
 */
logLine('', $quiet);
logLine('==================== SUMMARY ====================', $quiet);
logLine('Properties processed : '.$stats['properties'], $quiet);
logLine('Already on disk      : '.$stats['images_ok'], $quiet);
logLine('Downloaded           : '.$stats['images_downloaded'], $quiet);
logLine('Placeholder (offline): '.$stats['images_placeholder'], $quiet);
logLine('Failed               : '.$stats['images_failed'], $quiet);
logLine('Records created      : '.$stats['records_created'], $quiet);
logLine('Paths rebound        : '.$stats['paths_rebound'], $quiet);
logLine('Covers set           : '.$stats['covers_set'], $quiet);

if ($stats['images_failed'] > 0) {
    exit(1);
}
exit(0);