@php $statusLabels = ['draft'=>'مسودة','published'=>'منشور','archived'=>'مؤرشف']; @endphp
<x-admin.layouts.admin heading="Email Template Studio" title="استوديو قوالب البريد">
<div x-data="emailTemplateStudio()" x-init="init()" class="space-y-4">
<form id="templateForm" method="POST" action="{{ route('admin.email-templates.update',$template) }}" @submit="prepareSubmit()" class="space-y-4">
@csrf @method('PATCH')
<input type="hidden" name="html_content" id="htmlContentField"><input type="hidden" name="css_styles" id="cssStylesField"><input type="hidden" name="variables" id="variablesField">
<section class="rounded-2xl border border-gray-200 bg-white p-3 shadow-sm dark:border-gray-700 dark:bg-gray-900">
<div class="flex flex-wrap items-center gap-2">
<div class="min-w-[260px] flex-1"><input name="name" value="{{ old('name',$template->name) }}" required maxlength="190" class="w-full border-0 bg-transparent p-0 text-lg font-black outline-none focus:ring-0"><div class="mt-1 text-xs text-gray-500">{{ $template->key }} · v{{ $template->version }}</div></div>
<span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-black dark:bg-gray-800" x-text="statusLabel"></span><span class="text-xs font-bold text-gray-500" x-text="saveStatus"></span>
<a href="{{ route('admin.email-templates.history',$template) }}" class="rounded-lg border px-3 py-2 text-sm font-black">السجل</a>
<button type="button" @click="publish" :disabled="busy" class="rounded-lg bg-wajhatak-600 px-3 py-2 text-sm font-black text-white disabled:opacity-50">نشر الإصدار</button>
@if(!$template->is_system)<button type="button" @click="archive" :disabled="busy" class="rounded-lg border border-red-200 px-3 py-2 text-sm font-black text-red-700 disabled:opacity-50">أرشفة</button>@endif
<button type="submit" :disabled="busy" class="rounded-lg bg-gray-900 px-3 py-2 text-sm font-black text-white dark:bg-gray-100 dark:text-gray-900 disabled:opacity-50">حفظ الإصدار</button>
</div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-3 shadow-sm dark:border-gray-700 dark:bg-gray-900">
<label class="mb-1 block text-xs font-black text-gray-500">موضوع الرسالة</label>
<input name="subject" x-model="subject" value="{{ old('subject',$template->subject) }}" required maxlength="190" class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-800">
<textarea name="description" rows="2" class="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-800" placeholder="وصف القالب">{{ old('description',$template->description) }}</textarea>
</section>
<div class="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(360px,0.8fr)]">
<section class="min-w-0 overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900">
<div class="flex flex-wrap items-center gap-2 border-b border-gray-200 p-3 dark:border-gray-700">
<button type="button" @click="switchMode('visual')" :class="mode==='visual'?'bg-wajhatak-600 text-white':'bg-gray-100 dark:bg-gray-800'" class="rounded-lg px-3 py-2 text-sm font-black">المحرر المرئي</button>
<button type="button" @click="switchMode('code')" :class="mode==='code'?'bg-wajhatak-600 text-white':'bg-gray-100 dark:bg-gray-800'" class="rounded-lg px-3 py-2 text-sm font-black">HTML / CSS</button>
<button type="button" @click="insertVariablePrompt()" class="rounded-lg border px-3 py-2 text-sm font-black">إدراج متغير</button>
<button type="button" @click="$refs.assetInput.click()" class="rounded-lg border px-3 py-2 text-sm font-black">إضافة صورة</button>
<button type="button" @click="showIcons=true" class="rounded-lg border px-3 py-2 text-sm font-black">مكتبة الأيقونات</button>
<input x-ref="assetInput" type="file" accept="image/png,image/jpeg,image/gif,image/webp" class="hidden" @change="uploadAsset($event)">
<button type="button" @click="showTest=true" class="ms-auto rounded-lg border border-wajhatak-200 px-3 py-2 text-sm font-black text-wajhatak-700">إرسال تجريبي</button>
</div>
<div x-show="mode==='visual'" x-cloak><div id="gjs" class="min-h-[720px]"></div></div>
<div x-show="mode==='code'" x-cloak class="grid grid-rows-[520px_220px]"><div id="monacoHtml" class="border-b border-gray-200 dark:border-gray-700"></div><div id="monacoCss"></div></div>
</section>
<aside class="space-y-4">
<section class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900"><div class="mb-3 flex items-center justify-between"><h2 class="font-black">المعاينة</h2><div class="flex gap-1"><button type="button" @click="device='desktop';refreshPreview()" :class="device==='desktop'?'bg-gray-900 text-white':'bg-gray-100 dark:bg-gray-800'" class="rounded-lg px-2.5 py-1.5 text-xs font-black">سطح المكتب</button><button type="button" @click="device='mobile';refreshPreview()" :class="device==='mobile'?'bg-gray-900 text-white':'bg-gray-100 dark:bg-gray-800'" class="rounded-lg px-2.5 py-1.5 text-xs font-black">الجوال</button></div></div><div class="overflow-hidden rounded-xl border bg-gray-100 p-2 dark:bg-gray-950"><iframe id="previewFrame" title="معاينة البريد" sandbox referrerpolicy="no-referrer" class="mx-auto h-[620px] w-full rounded-lg bg-white"></iframe></div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900"><h2 class="mb-3 font-black">المتغيرات المركزية</h2><div class="max-h-72 space-y-1 overflow-y-auto">@foreach($variables as $key=>$definition)<button type="button" @click="insertVariable('{{ $key }}')" class="w-full rounded-lg border px-2.5 py-2 text-right"><div class="font-mono text-xs font-black">&#123;&#123;{{ $key }}&#125;&#125;</div><div class="mt-0.5 text-[11px] text-gray-500">{{ $definition['description'] }} · {{ $definition['type'] }}</div></button>@endforeach</div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900"><h2 class="mb-2 font-black">بيانات المعاينة</h2><div class="grid gap-2">@foreach($previewValues as $key=>$value)<label class="text-xs font-bold">{{ $key }}<input type="text" value="{{ is_scalar($value)?$value:'' }}" @input="previewValues['{{ $key }}']=$event.target.value;refreshPreviewDebounced()" class="mt-1 w-full rounded-lg border bg-gray-50 px-2.5 py-2 text-xs dark:bg-gray-800"></label>@endforeach</div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900"><h2 class="mb-2 font-black">النص البديل</h2><textarea name="text_content" x-model="textContent" rows="7" class="w-full rounded-xl border bg-gray-50 px-3 py-2.5 text-sm dark:bg-gray-800">{{ old('text_content',$template->text_content) }}</textarea></section>
</aside></div>
</form>
<div x-show="showIcons" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center bg-black/50 p-4" @keydown.escape.window="showIcons=false"><div class="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-2xl dark:bg-gray-900"><div class="flex items-center justify-between"><div><h2 class="text-lg font-black">مكتبة أيقونات جاهزة للبريد</h2><p class="text-xs text-gray-500">أيقونات نصية/Unicode آمنة نسبيًا عبر عملاء البريد، ويمكن استخدامها داخل الأزرار والعناوين.</p></div><button type="button" @click="showIcons=false" class="rounded-lg border px-3 py-2">إغلاق</button></div><div class="mt-4 grid grid-cols-5 gap-2 sm:grid-cols-8">@foreach(["✓","✕","★","☆","♥","♡","→","←","☎","✉","⌂","⚡","🔒","🔔","🏠","📍","📅","🕐","💬","⭐","🏷️","🔗","👤","⚙️","🎉","⚠️","ℹ️","✓️"] as $icon)<button type="button" @click="insertIcon(@js($icon));showIcons=false" class="flex h-14 items-center justify-center rounded-xl border text-2xl hover:border-wajhatak-500 hover:bg-wajhatak-50 dark:hover:bg-wajhatak-900/20">{{ $icon }}</button>@endforeach</div></div></div>
<div x-show="showTest" x-cloak class="fixed inset-0 z-[90] flex items-center justify-center bg-black/50 p-4"><div class="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl dark:bg-gray-900"><h2 class="text-lg font-black">إرسال بريد تجريبي حقيقي</h2><p class="mt-1 text-sm text-gray-500">سيستخدم موفر البريد الفعلي المهيأ في النظام.</p><input type="email" x-model="testRecipient" class="mt-4 w-full rounded-xl border bg-gray-50 px-3 py-2.5 dark:bg-gray-800"><div class="mt-4 flex justify-end gap-2"><button type="button" @click="showTest=false" class="rounded-lg border px-4 py-2 text-sm font-black">إلغاء</button><button type="button" @click="sendTest" :disabled="busy" class="rounded-lg bg-wajhatak-600 px-4 py-2 text-sm font-black text-white">إرسال الآن</button></div></div></div>
</div>
@push('scripts')
<link rel="stylesheet" href="https://unpkg.com/grapesjs@0.23.6/dist/css/grapes.min.css">
<script src="https://unpkg.com/grapesjs@0.23.6"></script><script src="https://unpkg.com/grapesjs-preset-newsletter@1.0.2"></script><script src="https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs/loader.js"></script>
<script>
function emailTemplateStudio() {
return {
mode:'visual',device:'desktop',busy:false,saveStatus:'Saved',showTest:false,showIcons:false,testRecipient:@json(auth()->user()->email),previewValues:@json($previewValues),status:@json($template->status ?: 'draft'),subject:@json($template->subject),textContent:@json($template->text_content ?: ''),initialHtml:@json($template->html_content ?: ''),initialCss:@json(is_array($template->css_styles)?implode("\n",$template->css_styles):($template->css_styles ?: '')),visualEditor:null,htmlEditor:null,cssEditor:null,autosaveTimer:null,previewTimer:null,autosaveController:null,previewController:null,
get statusLabel(){return @json($statusLabels)[this.status]||this.status;},
async init(){this.mountVisual();await this.loadMonaco();this.refreshPreview();},
mountVisual(){if(this.visualEditor||!window.grapesjs)return;this.visualEditor=grapesjs.init({container:'#gjs',height:'720px',storageManager:false,assetManager:{upload:@json(route('admin.email-templates.assets')),uploadName:'file',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content||''},params:{_token:document.querySelector('meta[name="csrf-token"]')?.content||''},autoAdd:true},plugins:['gjs-preset-newsletter'],pluginsOpts:{'gjs-preset-newsletter':{inlineCss:true,showBlocksOnLoad:true,updateStyleManager:true,blockLabel: 'كتل البريد'}},blockManager:{appendTo:'#gjs',blocks:[]},components:this.initialHtml||'<table role="presentation" width="100%"><tr><td style="padding:32px;text-align:center"><h1>عنوان الرسالة</h1><p>اكتب محتوى البريد هنا.</p></td></tr></table>',style:this.initialCss,deviceManager:{devices:[{name:'Desktop',width:'100%'},{name:'Mobile',width:'390px'}]}});this.visualEditor.on('component:update component:styleUpdate',()=>this.markDirty());},
async loadMonaco(){if(this.htmlEditor)return;await new Promise((resolve)=>{const start=()=>{require.config({paths:{vs:'https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs'}});require(['vs/editor/editor.main'],()=>{const theme=document.documentElement.classList.contains('dark')?'vs-dark':'vs';this.htmlEditor=monaco.editor.create(document.getElementById('monacoHtml'),{value:this.initialHtml,language:'html',theme,automaticLayout:true,minimap:{enabled:false},wordWrap:'on',tabSize:2,formatOnPaste:true,formatOnType:true});this.cssEditor=monaco.editor.create(document.getElementById('monacoCss'),{value:this.initialCss,language:'css',theme,automaticLayout:true,minimap:{enabled:false},wordWrap:'on',tabSize:2});this.htmlEditor.onDidChangeModelContent(()=>this.markDirty());this.cssEditor.onDidChangeModelContent(()=>this.markDirty());resolve();});};if(window.require?.config)start();else{const t=setInterval(()=>{if(window.require?.config){clearInterval(t);start();}},50);}});},
switchMode(next){if(next===this.mode)return;if(next==='code'){this.htmlEditor?.setValue(this.visualHtml());this.cssEditor?.setValue(this.visualCss());}else{this.visualEditor?.setComponents(this.htmlEditor?.getValue()||this.initialHtml);this.visualEditor?.setStyle(this.cssEditor?.getValue()||this.initialCss);}this.mode=next;this.refreshPreview();},
visualHtml(){if(!this.visualEditor)return this.initialHtml;try{return this.visualEditor.runCommand('gjs-get-inlined-html')||this.visualEditor.getHtml();}catch(_){return this.visualEditor.getHtml();}},
visualCss(){return this.visualEditor?.getCss()||this.initialCss;},
currentHtml(){return this.mode==='code'&&this.htmlEditor?this.htmlEditor.getValue():this.visualHtml();},
currentCss(){return this.mode==='code'&&this.cssEditor?this.cssEditor.getValue():this.visualCss();},
markDirty(){this.saveStatus='Unsaved changes';clearTimeout(this.autosaveTimer);this.autosaveTimer=setTimeout(()=>this.autosave(),3000);this.refreshPreviewDebounced();},
refreshPreviewDebounced(){clearTimeout(this.previewTimer);this.previewTimer=setTimeout(()=>this.refreshPreview(),600);},
getFormData(){const f=document.getElementById('templateForm');return{name:f.elements.name.value,description:f.elements.description.value,subject:f.elements.subject.value,html_content:this.currentHtml(),text_content:this.textContent,css_styles:[this.currentCss()],variables:@json(array_keys($variables)),preview_variables:this.previewValues};},
syncHidden(){document.getElementById('htmlContentField').value=this.currentHtml();document.getElementById('cssStylesField').value=JSON.stringify([this.currentCss()]);document.getElementById('variablesField').value=JSON.stringify(@json(array_keys($variables)));},
prepareSubmit(){this.syncHidden();this.saveStatus='Saving...';},
async refreshPreview(){this.previewController?.abort();this.previewController=new AbortController();try{const r=await fetch(@json(route('admin.email-templates.preview',$template)),{method:'POST',signal:this.previewController.signal,headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(this.getFormData())});const d=await r.json();if(!r.ok)return;const frame=document.getElementById('previewFrame');frame.style.maxWidth=this.device==='mobile'?'390px':'100%';frame.srcdoc=d.html||'<div style="padding:24px;font-family:Arial">لا يوجد محتوى HTML صالح.</div>';}catch(e){if(e.name!=='AbortError')console.error(e);}finally{if(this.previewController?.signal.aborted===false)this.previewController=null;}},
async autosave(){const payload=this.getFormData();this.autosaveController?.abort();this.autosaveController=new AbortController();this.saveStatus='Saving...';try{const r=await fetch(@json(route('admin.email-templates.autosave',$template)),{method:'POST',signal:this.autosaveController.signal,headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||'save_failed');this.status=d.status;this.saveStatus='Saved';return true;}catch(e){if(e.name!=='AbortError')this.saveStatus='Save failed';return false;}},
async publish(){if(this.busy)return;this.busy=true;try{if(!(await this.autosave()))throw new Error('تعذر حفظ المسودة؛ لم يتم النشر.');const r=await fetch(@json(route('admin.email-templates.publish',$template)),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}});const d=await r.json();if(!r.ok)throw new Error(d.message||'publish_failed');window.location.reload();}catch(e){alert(e.message||'تعذر نشر الإصدار.');}finally{this.busy=false;}},
async archive(){if(this.busy||!confirm('أرشفة القالب؟'))return;this.busy=true;try{const r=await fetch(@json(route('admin.email-templates.archive',$template)),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}});const d=await r.json();if(!r.ok)throw new Error(d.message||'archive_failed');window.location.reload();}catch(e){alert(e.message||'تعذر أرشفة القالب.');}finally{this.busy=false;}},
insertVariable(name){const token='{{' + name + '}}';if(this.mode==='code'&&this.htmlEditor){const s=this.htmlEditor.getSelection();this.htmlEditor.executeEdits('insert-variable',[{range:s,text:token,forceMoveMarkers:true}]);this.htmlEditor.focus();}else if(this.visualEditor){const selected=this.visualEditor.getSelected();const block='<p>'+token+'</p>';if(selected)selected.append(block);else this.visualEditor.addComponents(block);this.markDirty();}},
insertVariablePrompt(){const key=prompt('اسم المتغير، مثل user.name أو property.price');if(key&&@json(array_keys($variables)).includes(key))this.insertVariable(key);},
async uploadAsset(event){const file=event.target.files?.[0];event.target.value='';if(!file||this.busy)return;this.busy=true;try{const fd=new FormData();fd.append('file',file);const r=await fetch(@json(route('admin.email-templates.assets')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content||''},body:fd});const d=await r.json();if(!r.ok)throw new Error(d.message||'تعذر رفع الصورة');const asset=d.data?.[0];if(!asset?.src)throw new Error('لم يُرجع الخادم رابط الصورة');if(this.visualEditor){const selected=this.visualEditor.getSelected();const component={type:'image',src:asset.src,alt:asset.name||'صورة البريد',style:{'max-width':'100%','height':'auto','display':'block','margin':'0 auto'}};if(selected)selected.append(component);else this.visualEditor.addComponents(component);}this.markDirty();}catch(e){alert(e.message||'تعذر رفع الصورة.');}finally{this.busy=false;}},
insertIcon(icon){const html='<span style="font-size:24px;line-height:1;display:inline-block">'+icon+'</span>';if(this.mode==='code'&&this.htmlEditor){const s=this.htmlEditor.getSelection();this.htmlEditor.executeEdits('insert-icon',[{range:s,text:html,forceMoveMarkers:true}]);this.htmlEditor.focus();}else if(this.visualEditor){const selected=this.visualEditor.getSelected();if(selected)selected.append(html);else this.visualEditor.addComponents(html);this.markDirty();}},
async sendTest(){if(this.busy||!this.testRecipient)return;this.busy=true;try{const payload=this.getFormData();payload.recipient=this.testRecipient;const r=await fetch(@json(route('admin.email-templates.test-email',$template)),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||'send_failed');alert(d.message||'تم إرسال البريد التجريبي.');this.showTest=false;}catch(e){alert(e.message||'تعذر إرسال البريد التجريبي.');}finally{this.busy=false;}}
};
}
</script>
@endpush
</x-admin.layouts.admin>
